######################################################################
##
## Filename: fft_tb.fdo
## Created on: Mon Jun 20 9:46:19 中国标准时间 2016
##
##  Auto generated by Project Navigator for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the project directory and will not be removed on
##  subsequent simulation flows run from Project Navigator.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#
# Create work library
#
vlib work
#
# Compile sources
#
vlog     "../../src/core/xilinx/fft.v"
vlog     "../../src/preproc.v"
vlog     "../../src/postproc.v"
vlog     "../../src/testbench/fft_source_bfm.v"
vlog -sv "../../src/testbench/reset_source.sv"         
vlog -sv "../../src/testbench/clock_source.sv"
vlog     "../../src/LTE_FFT.v"
vlog     "../../src/testbench/fft_tb.v"
vlog     "C:/Xilinx/14.7/ISE_DS/ISE//verilog/src/glbl.v"
#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps  -L xilinxcorelib_ver -L unisims_ver -L unimacro_ver -L secureip -lib work work.fft_tb glbl
#
# Source the wave do file
#
do {xilinx_wave.do}
#
# Run simulation for this time
#
run 400us
#
# End
#
