######################################################################
##
## Filename: fft_tb.udo
## Created on: Mon Jun 20 9:46:19 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
